swagger: '2.0'
info:
  title: cheqd-node - Tendermint RPC APIs
  description: 'Tendermint RPC for identity functionality in cheqd-node. This document describes the APIs for creating, updating, and querying Decentralized Identifiers (DIDs) using the `did:cheqd` method.'
  version: 1.0.0


paths:
  /getDid:
    get:
      tags:
        - Query requests
      summary: return DID
      operationId: returnDid
      description: Returns DID Document from the ledger by DID
      produces:
        - application/json
      parameters:
        - in: query
          name: id
          description: Fully-qualified DID of type `did:cheqd:<namespace>` which already exists on a cheqd network ledger.
          required: true
          type: string
      responses:
        "200":
          description: DID Document
          schema:
            $ref: '#/definitions/StateValue'
        x-1201:
          description: No DID Document correlating to DID found on the ledger
  
  /createDid:
    post:
      tags:
        - Write requests
      summary: Create a new DID and associated DID Document on ledger
      operationId: createDid
      description: Creates a new DID using the `did:cheqd` method along with associated DID Document representation.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          description: Signed request for creating DID Document
          schema:
            $ref: '#/definitions/MsgCreateDid'
      responses:
        "201":
          description: DID created
          schema:
            $ref: '#/definitions/MsgCreateDidResponse'
        x-1000:
          description: The request the client made is incorrect or corrupt
        x-1001:
          description: The request does not contain required properties
        x-1002:
          description: The request contains invalid `id` property
        x-1003:
          description: The request contains invalid Verification Method
        x-1004:
          description: The request contains invalid Service
        x-1005:
          description: The request contains invalid Verification Method ID
        x-1100:
          description: Invalid signature detected
        x-1200:
          description: Attempt to create a DID / DID Document that already exists on ledger
        x-1202:
          description: The DID Document does not contain required Verification Method
        x-1204:
          description: Unable to decode public key
        x-1304:
          description: Unable to set value to the ledger
        x-1504:
          description: The method is not implemented

  /updateDid:
    post:
      tags:
        - Write requests
      summary: Update DID Document associatd with an existing DID
      operationId: updateDid
      description: Update DID Document associated with an existing DID of type `did:cheqd:<namespace>`.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          description: Signed request for updating DID Document
          schema:
            $ref: '#/definitions/MsgUpdateDid'
      responses:
        "201":
          description: DID Document updated
          schema:
            $ref: '#/definitions/MsgUpdateDidResponse'
        x-1000:
          description: The request the client made is incorrect or corrupt
        x-1001:
          description: The request does not contain required properties
        x-1002:
          description: The request contains invalid `id` property
        x-1003:
          description: The request contains invalid Verification Method
        x-1004:
          description: The request contains invalid Service
        x-1005:
          description: The request contains invalid Verification Method ID
        x-1100:
          description: Invalid signature detected
        x-1201:
          description: No DID Document founder on specified ledger
        x-1202:
          description: The DID Document does not contain required Verification Method
        x-1203:
          description: Potential replay attack detected. An attempt to was made to update the DID Document with incorrect version ID.
        x-1204:
          description: Unable to decode public key
        x-1304:
          description: Unable to set value to the ledger
        x-1504:
          description: The method is not implemented


definitions:
  SignInfo:
    required:
      - verificationMethodId
      - signature
    properties:
      verificationMethodId:
        description: URI from `DIDDoc.authentication`
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#verkey
      signature:
        description: Multiple Verification Methods and corresponding signatures can be added here
        type: string
        example: 49W5WP5jr7x1fZhtpAhHFbuUDqUYZ3AKht88gUjrz8TEJZr5MZUPjskpfBFdboLPZXKjbGjutoVascfKiMD5W7Ba

  MsgCreateDid:
    type: object
    required:
      - payload
      - signatures
    properties:
      payload:
        $ref: '#/definitions/MsgCreateDidPayload'
      signatures:
        description: Payload should be signed by all `controller` private keys. The `signatures` must contains signatures from all controllers.
        type: array
        items:
          $ref: '#/definitions/SignInfo'

  MsgCreateDidPayload:
    required:
      - id
    properties:
      context:
        description: A list of strings with links or JSONs for describing specifications that this DID Document is following to.
        type: array
        items:
          type: string
          example: "https://www.w3.org/ns/did/v1"
      id:
        description: Target DID as base58-encoded string for 16 or 32 byte DID value with cheqd DID Method prefix `did:cheqd:<namespace>:`.
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB
      verificationMethod:
        description: A list of Verification Methods
        type: array
        items:
          $ref: '#/definitions/VerificationMethod'
      controller:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue
      authentication:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      assertionMethod:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityInvocation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityDelegation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      keyAgreement:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      alsoKnownAs:
        description: A list of strings. A DID subject can have multiple identifiers for different purposes, or at different times. The assertion that two or more DIDs refer to the same DID subject can be made using the `alsoKnownAs` property.
        type: array
        items:
          type: string
      service:
        description: A set of Service Endpoint maps
        type: array
        items:
          $ref: '#/definitions/Service'

  MsgCreateDidResponse:
    required:
      - id
    properties:
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB


  MsgUpdateDid:
    type: object
    required:
      - payload
      - signatures
    properties:
      payload:
        $ref: '#/definitions/MsgUpdateDidPayload'
      signatures:
        description: Payload should be signed by all `controller` private keys. The `signatures` must contains signatures from all controllers.
        type: array
        items:
          $ref: '#/definitions/SignInfo'


  MsgUpdateDidPayload:
    required:
      - id
      - versionId
    properties:
      context:
        description: A list of strings with links or JSONs for describing specifications that this DID Document is following to.
        type: array
        items:
          type: string
          example: "https://www.w3.org/ns/did/v1"
      id:
        description: Target DID as base58-encoded string for 16 or 32 byte DID value with cheqd DID Method prefix `did:cheqd:<namespace>:`.
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB
      verificationMethod:
        description: A list of Verification Methods
        type: array
        items:
          $ref: '#/definitions/VerificationMethod'
      controller:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue
      authentication:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      assertionMethod:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityInvocation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityDelegation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      keyAgreement:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      alsoKnownAs:
        description: A list of strings. A DID subject can have multiple identifiers for different purposes, or at different times. The assertion that two or more DIDs refer to the same DID subject can be made using the `alsoKnownAs` property.
        type: array
        items:
          type: string
      service:
        description: A set of Service Endpoint maps
        type: array
        items:
          $ref: '#/definitions/Service'
      versionId:
        description: Should be filled by a transaction hash of the previous DID Document version. Can be received by `/getDid` query. It is needed for a replay protection.
        type: string
        example: 1B3B00849B4D50E8FCCF50193E35FD6CA5FD4686ED6AD8F847AC8C5E466CFD3E

  MsgUpdateDidResponse:
    required:
      - id
    properties:
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB


  StateValue:
    required:
      - data
      - metadata
    properties:
      data:
        $ref: '#/definitions/Did'
      metadata:
        $ref: '#/definitions/Metadata'

  Metadata:
    required:
      - created
      - updated
      - deactivated
      - versionId
    properties:
      created:
        description: Formatted as an XML Datetime normalized to UTC 00:00:00 and without sub-second decimal precision.
        type: string
        example: 2020-12-20T19:17:47Z
      updated:
        description: The value of the property MUST follow the same formatting rules as the created property. The `updated` field is null if an Update operation has never been performed on the DID document. If an updated property exists, it can be the same value as the created property when the difference between the two timestamps is less than one second.
        type: string
        example: 2020-12-20T19:17:47Z
      deactivated:
        description: If DID has been deactivated, DID document metadata MUST include this property with the boolean value true. By default this is set to `false`.
        type: boolean
        example: false
      versionId:
        description: Contains transaction hash of the current DID Document version.
        type: string
        example: 1B3B00849B4D50E8FCCF50193E35FD6CA5FD4686ED6AD8F847AC8C5E466CFD3E

  Did:
    required:
      - id
    properties:
      context:
        description: A list of strings with links or JSONs for describing specifications that this DID Document is following to.
        type: array
        items:
          type: string
          example: "https://www.w3.org/ns/did/v1"
      id:
        description: Target DID as base58-encoded string for 16 or 32 byte DID value with cheqd DID Method prefix `did:cheqd:<namespace>:`.
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB
      verificationMethod:
        description: A list of Verification Methods
        type: array
        items:
          $ref: '#/definitions/VerificationMethod'
      controller:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue
      authentication:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      assertionMethod:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityInvocation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      capabilityDelegation:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      keyAgreement:
        description: A list of strings with key aliases or IDs
        type: array
        items:
          type: string
          example: "did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key1"
      alsoKnownAs:
        description: A list of strings. A DID subject can have multiple identifiers for different purposes, or at different times. The assertion that two or more DIDs refer to the same DID subject can be made using the `alsoKnownAs` property.
        type: array
        items:
          type: string
      service:
        description: A set of Service Endpoint maps
        type: array
        items:
          $ref: '#/definitions/Service'

  Service:
    required:
      - id
      - type
      - serviceEndpoint
    properties:
      id:
        description: The value of the `id` property for a Service MUST be a URI conforming to [RFC3986](http://www.rfc-editor.org/rfc/rfc3986). A conforming producer MUST NOT produce multiple service entries with the same ID.
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#linked-domain
      type:
        description: The service type and its associated properties SHOULD be registered in the [DID Specification Registries](https://www.w3.org/TR/did-spec-registries/)
        type: string
        example: LinkedDomains
      serviceEndpoint:
        description: A string that conforms to the rules of [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) for URIs, a map, or a set composed of a one or more strings that conform to the rules of [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) for URIs and/or maps.
        type: string
        example: https://bar.example.com

  VerificationMethod :
    description: Only one of `publicKeyJwk` or `publicKeyMultibase` must exist
    required:
      - id
      - type
      - controller
    properties:
      id:
        description: A string with format `did:cheqd:<namespace>:<unique-id>#<key-alias>`
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key-0
      type:
        type: string
        example: Ed25519VerificationKey2020
      controller:
        description: A string with fully qualified DID. DID must exist.
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue
      publicKeyJwk:
        description: A map representing a JSON Web Key that conforms to [RFC7517](https://tools.ietf.org/html/rfc7517). See definition of `publicKeyJwk` for additional constraints.
        type: object
      publicKeyMultibase:
        description: A base58-encoded string that conforms to a [MULTIBASE](https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-03) encoded public key.
        type: string
        example: zAKJP3f7BD6W4iWEQ9jwndVTCBq8ua2Utt8EEjJ6Vxsf