swagger: '2.0'
info:
  title: cheqd Network - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for cheqd network.
  version: v2.x
contact:
  name: Cheqd Foundation Limited
  url: https://cheqd.io
license:
  name: Apache 2.0
  url: https://github.com/cheqd/cheqd-node/blob/main/LICENSE
host: localhost:1317
basePath: /swagger/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /cheqd/did/v2/{id}:
    get:
      operationId: DidDoc
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              value:
                type: object
                properties:
                  did_doc:
                    type: object
                    properties:
                      context:
                        type: array
                        items:
                          type: string
                      id:
                        type: string
                      controller:
                        type: array
                        items:
                          type: string
                      verification_method:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            verification_method_type:
                              type: string
                            controller:
                              type: string
                            verification_material:
                              type: string
                      authentication:
                        type: array
                        items:
                          type: string
                      assertion_method:
                        type: array
                        items:
                          type: string
                      capability_invocation:
                        type: array
                        items:
                          type: string
                      capability_delegation:
                        type: array
                        items:
                          type: string
                      key_agreement:
                        type: array
                        items:
                          type: string
                      service:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            service_type:
                              type: string
                            service_endpoint:
                              type: array
                              items:
                                type: string
                      also_known_as:
                        type: array
                        items:
                          type: string
                  metadata:
                    type: object
                    properties:
                      created:
                        type: string
                      updated:
                        type: string
                      deactivated:
                        type: boolean
                      version_id:
                        type: string
                      next_version_id:
                        type: string
                      previous_version_id:
                        type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: id
          description: is a DID to be fetched
          in: path
          required: true
          type: string
      tags:
        - Query
  /cheqd/did/v2/{id}/metadata:
    get:
      operationId: AllDidDocVersionsMetadata
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              versions:
                type: array
                items:
                  type: object
                  properties:
                    created:
                      type: string
                    updated:
                      type: string
                    deactivated:
                      type: boolean
                    version_id:
                      type: string
                    next_version_id:
                      type: string
                    previous_version_id:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: id
          description: is a DID
          in: path
          required: true
          type: string
      tags:
        - Query
  /cheqd/did/v2/{id}/version/{version}:
    get:
      operationId: DidDocVersion
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              value:
                type: object
                properties:
                  did_doc:
                    type: object
                    properties:
                      context:
                        type: array
                        items:
                          type: string
                      id:
                        type: string
                      controller:
                        type: array
                        items:
                          type: string
                      verification_method:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            verification_method_type:
                              type: string
                            controller:
                              type: string
                            verification_material:
                              type: string
                      authentication:
                        type: array
                        items:
                          type: string
                      assertion_method:
                        type: array
                        items:
                          type: string
                      capability_invocation:
                        type: array
                        items:
                          type: string
                      capability_delegation:
                        type: array
                        items:
                          type: string
                      key_agreement:
                        type: array
                        items:
                          type: string
                      service:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            service_type:
                              type: string
                            service_endpoint:
                              type: array
                              items:
                                type: string
                      also_known_as:
                        type: array
                        items:
                          type: string
                  metadata:
                    type: object
                    properties:
                      created:
                        type: string
                      updated:
                        type: string
                      deactivated:
                        type: boolean
                      version_id:
                        type: string
                      next_version_id:
                        type: string
                      previous_version_id:
                        type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: id
          description: is a DID
          in: path
          required: true
          type: string
        - name: version
          description: is a unique value that maps DID Doc state at some point
          in: path
          required: true
          type: string
      tags:
        - Query
  /cheqd/resource/v2/{collection_id}/metadata:
    get:
      operationId: CollectionResources
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              resources:
                type: array
                items:
                  type: object
                  properties:
                    collection_id:
                      type: string
                    id:
                      type: string
                    name:
                      type: string
                    version:
                      type: string
                    resource_type:
                      type: string
                    also_known_as:
                      type: array
                      items:
                        type: object
                        properties:
                          uri:
                            type: string
                          description:
                            type: string
                    media_type:
                      type: string
                    created:
                      type: string
                    checksum:
                      type: string
                    previous_version_id:
                      type: string
                    next_version_id:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: collection_id
          description: is unique identifier a for collection
          in: path
          required: true
          type: string
      tags:
        - Query
  /cheqd/resource/v2/{collection_id}/resources/{id}:
    get:
      operationId: Resource
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              resource:
                type: object
                properties:
                  resource:
                    type: object
                    properties:
                      data:
                        type: string
                        format: byte
                  metadata:
                    type: object
                    properties:
                      collection_id:
                        type: string
                      id:
                        type: string
                      name:
                        type: string
                      version:
                        type: string
                      resource_type:
                        type: string
                      also_known_as:
                        type: array
                        items:
                          type: object
                          properties:
                            uri:
                              type: string
                            description:
                              type: string
                      media_type:
                        type: string
                      created:
                        type: string
                      checksum:
                        type: string
                      previous_version_id:
                        type: string
                      next_version_id:
                        type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: collection_id
          description: is unique identifier a for collection
          in: path
          required: true
          type: string
        - name: id
          description: is unique identifier for a resource
          in: path
          required: true
          type: string
      tags:
        - Query
  /cheqd/resource/v2/{collection_id}/resources/{id}/metadata:
    get:
      operationId: ResourceMetadata
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              resource:
                type: object
                properties:
                  collection_id:
                    type: string
                  id:
                    type: string
                  name:
                    type: string
                  version:
                    type: string
                  resource_type:
                    type: string
                  also_known_as:
                    type: array
                    items:
                      type: object
                      properties:
                        uri:
                          type: string
                        description:
                          type: string
                  media_type:
                    type: string
                  created:
                    type: string
                  checksum:
                    type: string
                  previous_version_id:
                    type: string
                  next_version_id:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: collection_id
          description: is unique identifier a for collection
          in: path
          required: true
          type: string
        - name: id
          description: is unique identifier for a resource
          in: path
          required: true
          type: string
      tags:
        - Query
