FROM ghcr.io/cheqd/cheqd-node:latest

ARG HOME_DIR="/home/cheqd"
ARG CHEQD_ROOT_DIR="${HOME_DIR}/.cheqdnode/"
ARG USER="cheqd"

ARG UID=1000
ARG GID=${UID}

USER root
RUN apk update && apk add --no-cache jq

COPY --chown=${USER}:${GROUP} ../localnet/gen-network-config.sh /bin/gen-network
COPY --chown=${USER}:${GROUP} ../localnet/import-keys.sh /bin/import-keys
COPY --chown=${USER}:${GROUP} ../localnet/container-env/validator-0.env ${HOME_DIR}
COPY --chown=${USER}:${GROUP} ./testnet.sh /bin/run-testnet
RUN chmod +rx /bin/run-testnet

USER ${USER}
WORKDIR ${HOME_DIR}

EXPOSE 26656
EXPOSE 26657
EXPOSE 1317
EXPOSE 9090
EXPOSE 9091

CMD ["run-testnet"]