#!/bin/bash

# Get rid of systemd service
if test -f "/etc/systemd/system/cheqd-noded.service"; then
    rm /etc/systemd/system/cheqd-noded.service
    # Reload systemd daemons
    systemctl daemon-reload
fi

