#!/bin/bash

# Tweaks network configuration generated by `../tools/gen-network-config.sh` for use with docker-localnet container.

set -euo pipefail

# Generate base network configuration
bash ../tools/gen-network-config-base.sh cheqd 4 1 1 # 4 validators, 1 observer and 1 seed

# Set peers
SEED_0_ID=$(cheqd-noded tendermint show-node-id --home "network-config/seed-0")
PERSISTENT_PEERS="$SEED_0_ID@seed-0:26656"
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/validator-0/config/config.toml
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/validator-1/config/config.toml
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/validator-2/config/config.toml
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/validator-3/config/config.toml
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/observer-0/config/config.toml
