version: '3.2'

services:
  cheqd:
    image: cheqd
    build:
      context: ./cheqd
      dockerfile: cheqd.Dockerfile
    ports:
      - "26656:26656" # p2p
      - "26657:26657" # rpc

  osmosis:
    image: osmosis
    build:
      context: ./osmosis
      dockerfile: osmosis.Dockerfile
    ports:
      - "26666:26656" # p2p
      - "26667:26657" # rpc
