version: '3.2'

services:
  cheqd:
    image: cheqd
    build:
      context: ./cheqd
      dockerfile: cheqd.Dockerfile
    ports:
      - "26656:26656" # p2p
      - "26657:26657" # rpc
      - "9090:9090" # grpc
      - "9091:9091" # grpc-web

  osmosis:
    image: osmosis
    build:
      context: ./osmosis
      dockerfile: osmosis.Dockerfile
    ports:
      - "26666:26656" # p2p
      - "26667:26657" # rpc
      - "9190:9090" # grpc
      - "9191:9091" # grpc-web

  hermes:
    image: hermes
    build:
      context: ./hermes
      dockerfile: hermes.Dockerfile
    ports:
      - "3000:3000" # rest
      - "3001:3001" # telemetry
    entrypoint: tail -f /dev/null
