@startuml
!pragma teoz true
hide footbox

actor Client
participant Universal_Resolver
participant Cheqd_DID_Driver
database Ledger


note over Universal_Resolver
    https://dev.uniresolver.io
end note

/ note over Cheqd_DID_Driver
    Cheqd web service
end note

/ note over Ledger
    Cheqd seed node
end note



Client ->>  Universal_Resolver: GET /1.0/identifiers/{DID}
Activate Universal_Resolver
Universal_Resolver ->> Cheqd_DID_Driver: GET /1.0/identifiers/{DID}

Activate Cheqd_DID_Driver
Cheqd_DID_Driver ->> Ledger

Activate Ledger
Cheqd_DID_Driver <<- Ledger: proto:DIDDoc

Deactivate Ledger
Cheqd_DID_Driver <<- Cheqd_DID_Driver: Marshall proto to JSON \naccording DID spec

Universal_Resolver <<- Cheqd_DID_Driver: JSON:DIDDoc


Deactivate Ledger

Client <<- Universal_Resolver: JSON:DIDDoc
Deactivate Universal_Resolver


@enduml
