// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cheqd/did/v2/fee.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeRange struct {
	// Denomination of the token (e.g., "ncheq")
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// Minimum fee amount allowed (stored as string for large values)
	MinAmount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=min_amount,json=minAmount,proto3,customtype=cosmossdk.io/math.Int" json:"min_amount"`
	// Maximum fee amount allowed (stored as string for large values)
	MaxAmount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3,customtype=cosmossdk.io/math.Int" json:"max_amount"`
}

func (m *FeeRange) Reset()         { *m = FeeRange{} }
func (m *FeeRange) String() string { return proto.CompactTextString(m) }
func (*FeeRange) ProtoMessage()    {}
func (*FeeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0cfbae270deaac7, []int{0}
}
func (m *FeeRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRange.Merge(m, src)
}
func (m *FeeRange) XXX_Size() int {
	return m.Size()
}
func (m *FeeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRange.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRange proto.InternalMessageInfo

func (m *FeeRange) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type FeeParams struct {
	// Range-based fee for creating a DID
	CreateDid []FeeRange `protobuf:"bytes,1,rep,name=create_did,json=createDid,proto3" json:"create_did"`
	// Range-based fee for updating a DID
	UpdateDid []FeeRange `protobuf:"bytes,2,rep,name=update_did,json=updateDid,proto3" json:"update_did"`
	// Range-based fee for deactivating a DID
	DeactivateDid []FeeRange `protobuf:"bytes,3,rep,name=deactivate_did,json=deactivateDid,proto3" json:"deactivate_did"`
	// Percentage of the fixed fee that will be burned
	//
	// Default: 0.5 (50%)
	BurnFactor cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=burn_factor,json=burnFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"burn_factor"`
}

func (m *FeeParams) Reset()         { *m = FeeParams{} }
func (m *FeeParams) String() string { return proto.CompactTextString(m) }
func (*FeeParams) ProtoMessage()    {}
func (*FeeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0cfbae270deaac7, []int{1}
}
func (m *FeeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeParams.Merge(m, src)
}
func (m *FeeParams) XXX_Size() int {
	return m.Size()
}
func (m *FeeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeeParams proto.InternalMessageInfo

func (m *FeeParams) GetCreateDid() []FeeRange {
	if m != nil {
		return m.CreateDid
	}
	return nil
}

func (m *FeeParams) GetUpdateDid() []FeeRange {
	if m != nil {
		return m.UpdateDid
	}
	return nil
}

func (m *FeeParams) GetDeactivateDid() []FeeRange {
	if m != nil {
		return m.DeactivateDid
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeRange)(nil), "cheqd.did.v2.FeeRange")
	proto.RegisterType((*FeeParams)(nil), "cheqd.did.v2.FeeParams")
}

func init() { proto.RegisterFile("cheqd/did/v2/fee.proto", fileDescriptor_b0cfbae270deaac7) }

var fileDescriptor_b0cfbae270deaac7 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0x14, 0x31,
	0x14, 0xc7, 0x37, 0xbb, 0x55, 0xdc, 0x54, 0x05, 0x87, 0x5a, 0xc6, 0x8a, 0x69, 0xe9, 0xc5, 0x22,
	0x34, 0xa1, 0x2b, 0x78, 0xd1, 0x8b, 0xeb, 0xba, 0x20, 0x78, 0x90, 0xb9, 0x08, 0x5e, 0x86, 0x4c,
	0xf2, 0x3a, 0x1b, 0x24, 0xc9, 0x3a, 0x93, 0x19, 0xb6, 0xdf, 0xc2, 0x0f, 0xe0, 0xcd, 0x4b, 0x8f,
	0x1e, 0xfc, 0x10, 0x3d, 0x16, 0x4f, 0xe2, 0xa1, 0xc8, 0xec, 0xc1, 0xaf, 0x21, 0x93, 0xcc, 0xa0,
	0xd0, 0xcb, 0x5e, 0xc2, 0xbc, 0xf7, 0xfe, 0xbf, 0x7f, 0x98, 0x7f, 0x1e, 0xde, 0x15, 0x0b, 0xf8,
	0x24, 0x99, 0x54, 0x92, 0xd5, 0x13, 0x76, 0x0a, 0x40, 0x97, 0x85, 0x75, 0x36, 0xba, 0xed, 0xfb,
	0x54, 0x2a, 0x49, 0xeb, 0xc9, 0xde, 0x3d, 0xae, 0x95, 0xb1, 0xcc, 0x9f, 0x41, 0xb0, 0x47, 0x84,
	0x2d, 0xb5, 0x2d, 0x59, 0xc6, 0x4b, 0x60, 0xf5, 0x49, 0x06, 0x8e, 0x9f, 0x30, 0x61, 0x95, 0xe9,
	0xe6, 0x0f, 0xc2, 0x3c, 0xf5, 0x15, 0x0b, 0x45, 0x37, 0xda, 0xc9, 0x6d, 0x6e, 0x43, 0xbf, 0xfd,
	0x0a, 0xdd, 0xc3, 0x2f, 0x08, 0xdf, 0x9a, 0x03, 0x24, 0xdc, 0xe4, 0x10, 0xed, 0xe0, 0x1b, 0x12,
	0x8c, 0xd5, 0x31, 0x3a, 0x40, 0x47, 0xe3, 0x24, 0x14, 0xd1, 0x0b, 0x8c, 0xb5, 0x32, 0x29, 0xd7,
	0xb6, 0x32, 0x2e, 0x1e, 0xb6, 0xa3, 0xe9, 0xa3, 0x8b, 0xab, 0xfd, 0xc1, 0xaf, 0xab, 0xfd, 0xfb,
	0xe1, 0x8a, 0x52, 0x7e, 0xa4, 0xca, 0x32, 0xcd, 0xdd, 0x82, 0xbe, 0x31, 0x2e, 0x19, 0x6b, 0x65,
	0x5e, 0x7a, 0xbd, 0xa7, 0xf9, 0xaa, 0xa7, 0x47, 0x9b, 0xd1, 0x7c, 0x15, 0xe8, 0xc3, 0xaf, 0x43,
	0x3c, 0x9e, 0x03, 0xbc, 0xe3, 0x05, 0xd7, 0x65, 0xf4, 0x1c, 0x63, 0x51, 0x00, 0x77, 0x90, 0x4a,
	0x25, 0x63, 0x74, 0x30, 0x3a, 0xda, 0x9e, 0xec, 0xd2, 0xff, 0x33, 0xa3, 0xfd, 0xbf, 0x4c, 0xb7,
	0xda, 0x3b, 0x92, 0x71, 0xd0, 0xcf, 0x94, 0x6c, 0xe1, 0x6a, 0x29, 0x7b, 0x78, 0xb8, 0x09, 0x1c,
	0xf4, 0x2d, 0xfc, 0x0a, 0xdf, 0x95, 0xc0, 0x85, 0x53, 0x75, 0x6f, 0x30, 0xda, 0xc0, 0xe0, 0xce,
	0x3f, 0xa6, 0x35, 0x79, 0x8f, 0xb7, 0xb3, 0xaa, 0x30, 0xe9, 0x29, 0x17, 0xce, 0x16, 0xf1, 0x96,
	0xcf, 0xe2, 0x59, 0x97, 0xc5, 0xc3, 0xeb, 0x59, 0xbc, 0x85, 0x9c, 0x8b, 0xb3, 0x19, 0x88, 0x1f,
	0xdf, 0x8f, 0x71, 0xf7, 0x96, 0x33, 0x10, 0xe7, 0x7f, 0xbe, 0x3d, 0x41, 0x09, 0x6e, 0xad, 0xe6,
	0xde, 0x69, 0xfa, 0xfa, 0xbc, 0x21, 0xe8, 0xa2, 0x21, 0xe8, 0xb2, 0x21, 0xe8, 0x77, 0x43, 0xd0,
	0xe7, 0x35, 0x19, 0x5c, 0xae, 0xc9, 0xe0, 0xe7, 0x9a, 0x0c, 0x3e, 0x3c, 0xce, 0x95, 0x5b, 0x54,
	0x19, 0x15, 0x56, 0xb3, 0xb0, 0x77, 0xfe, 0x3c, 0x36, 0x56, 0x02, 0x5b, 0xf9, 0x25, 0x74, 0x67,
	0x4b, 0x28, 0xb3, 0x9b, 0x7e, 0x25, 0x9e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x84, 0xcf,
	0xc4, 0x9e, 0x02, 0x00, 0x00,
}

func (this *FeeRange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeRange)
	if !ok {
		that2, ok := that.(FeeRange)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if !this.MinAmount.Equal(that1.MinAmount) {
		return false
	}
	if !this.MaxAmount.Equal(that1.MaxAmount) {
		return false
	}
	return true
}
func (this *FeeParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeParams)
	if !ok {
		that2, ok := that.(FeeParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.CreateDid) != len(that1.CreateDid) {
		return false
	}
	for i := range this.CreateDid {
		if !this.CreateDid[i].Equal(&that1.CreateDid[i]) {
			return false
		}
	}
	if len(this.UpdateDid) != len(that1.UpdateDid) {
		return false
	}
	for i := range this.UpdateDid {
		if !this.UpdateDid[i].Equal(&that1.UpdateDid[i]) {
			return false
		}
	}
	if len(this.DeactivateDid) != len(that1.DeactivateDid) {
		return false
	}
	for i := range this.DeactivateDid {
		if !this.DeactivateDid[i].Equal(&that1.DeactivateDid[i]) {
			return false
		}
	}
	if !this.BurnFactor.Equal(that1.BurnFactor) {
		return false
	}
	return true
}
func (m *FeeRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeRange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeRange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxAmount.Size()
		i -= size
		if _, err := m.MaxAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFee(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinAmount.Size()
		i -= size
		if _, err := m.MinAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFee(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFee(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BurnFactor.Size()
		i -= size
		if _, err := m.BurnFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFee(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.DeactivateDid) > 0 {
		for iNdEx := len(m.DeactivateDid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DeactivateDid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFee(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.UpdateDid) > 0 {
		for iNdEx := len(m.UpdateDid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UpdateDid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFee(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CreateDid) > 0 {
		for iNdEx := len(m.CreateDid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreateDid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFee(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintFee(dAtA []byte, offset int, v uint64) int {
	offset -= sovFee(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeRange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFee(uint64(l))
	}
	l = m.MinAmount.Size()
	n += 1 + l + sovFee(uint64(l))
	l = m.MaxAmount.Size()
	n += 1 + l + sovFee(uint64(l))
	return n
}

func (m *FeeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CreateDid) > 0 {
		for _, e := range m.CreateDid {
			l = e.Size()
			n += 1 + l + sovFee(uint64(l))
		}
	}
	if len(m.UpdateDid) > 0 {
		for _, e := range m.UpdateDid {
			l = e.Size()
			n += 1 + l + sovFee(uint64(l))
		}
	}
	if len(m.DeactivateDid) > 0 {
		for _, e := range m.DeactivateDid {
			l = e.Size()
			n += 1 + l + sovFee(uint64(l))
		}
	}
	l = m.BurnFactor.Size()
	n += 1 + l + sovFee(uint64(l))
	return n
}

func sovFee(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFee(x uint64) (n int) {
	return sovFee(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateDid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateDid = append(m.CreateDid, FeeRange{})
			if err := m.CreateDid[len(m.CreateDid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateDid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateDid = append(m.UpdateDid, FeeRange{})
			if err := m.UpdateDid[len(m.UpdateDid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeactivateDid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeactivateDid = append(m.DeactivateDid, FeeRange{})
			if err := m.DeactivateDid[len(m.DeactivateDid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFee(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFee
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFee
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFee
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFee
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFee        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFee          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFee = fmt.Errorf("proto: unexpected end of group")
)
