version: '3.8'

# SYNTAX: docker compose -f docker/localnet/generate-network/generate-network.yml up --detach

services:
  generate-network:
    build:
      context: docker/localnet/generate-network
      dockerfile: Dockerfile
      target: networkgen
      args:
        RELEASE_URL: https://github.com/cheqd/cheqd-node/releases/download/v0.3.1/cheqd-node_0.3.1.tar.gz
    # user: cheqd:cheqd
    # working_dir: /home/cheqd
    environment:
      - CHAIN_ID="cheqd"
      - VALIDATORS_COUNT=4
      - SEEDS_COUNT=1
      - OBSERVERS_COUNT=1
    entrypoint: [ "generate-network" ]
    restart: "no"
    # Volume definition defined below
#     volumes:
#       - type: volume
#         source: generate-network
#         target: /home/cheqd

# volumes:
#   generate-network:
