run:
  timeout: 10m
  # skip-dirs:
  #   - x/did/keeper/v1
  #   - x/did/types/v1
  #   - x/resource/keeper/v1
  #   - x/resource/types/v1


linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused


linters-settings:
  gofumpt:
    lang-version: "1.18"
    
  misspell:
    ignore-words:
      - cheqd
      - cheq
      - ncheq
