run:
  timeout: 5m


linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - gofumpt
    - govet
    - ineffassign
    - misspell
    - nestif
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck


linters-settings:

  gofumpt:
    lang-version: "1.17"
    
  misspell:
    ignore-words:
      - cheqd
