run:
  timeout: 5m


linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck


linters-settings:

  gofumpt:
    lang-version: "1.18"
    
  misspell:
    ignore-words:
      - cheqd
      - cheq
      - ncheq
