version: "2"

run:
  timeout: 10m
  go: "1.23"

linters:
  enable:
    - bodyclose
    - copyloopvar
    # - depguard # Disabled - no import restrictions applied earlier
    - dogsled
    - errcheck
    - goconst
    - gocritic
    # - gosimple # Merged into staticcheck in v2
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - staticcheck
    # - stylecheck # Merged into staticcheck in v2
    # - typecheck # Removed in v2
    - unconvert
    - unused

formatters:
  enable:
    - gofumpt
    - goimports


linters-settings:
  dogsled:
    # Checks assignments with too many blank identifiers.
    # Default: 2
    max-blank-identifiers: 3

  gocritic:
    # Which checks should be disabled; can't be combined with 'enabled-checks'.
    # See https://go-critic.github.io/overview#checks-overview.
    # Default: []
    disabled-checks:
      - regexpMust
      - badCall # Remove this after CI workflow PR
    
  misspell:
    ignore-words:
      - cheqd
      - cheq
      - ncheq

  staticcheck:
    # Select the Go version to target.
    go: "1.23"
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: ["all"]
    # https://staticcheck.io/docs/configuration/options/#dot_import_whitelist
    dot-import-whitelist:
      - "github.com/cheqd/cheqd-node/x/did/utils"
      - "github.com/onsi/gomega"
    # https://staticcheck.io/docs/configuration/options/#initialisms
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]

  goconst:
    min-occurrences: 5
    ignore-tests: true
    ignore-strings: "echo '"
