# Set threshold level (error | warning | info | style | ignore | none)
failure-threshold: warning

# List of ignored rules
# See list for reference: https://github.com/hadolint/hadolint#rules
ignored:

# Override default levels for specific rules
override:
  error:
  warning:
  info:
    - DL3008
    - DL3027
    - DL3018
    - DL3022
  style:
