# Set threshold level (error | warning | info | style | ignore | none)
failure-threshold: warning

# List of ignored rules
# See list for reference: https://github.com/hadolint/hadolint#rules
ignored:
  - DL3008

# Override default levels for specific rules
override:
  error:
  warning:
  info:
  style:
