---

##########################
##########################
## OpenAPI Linter rules ##
##########################
##########################

extends: spectral:oas

rules:
  oas2-schema: warn

ignore:
  - "app/client/docs/config.yaml"
