---

##########################
##########################
## OpenAPI Linter rules ##
##########################
##########################

extends: spectral:oas

overrides:
  files:
    - "api/docs/config.yaml"
