#!/bin/bash

# Tweaks network configuration generated by `../tools/gen-network-config.sh` for use with docker-localnet container.

set -euo pipefail

# Generate base network configuration
bash gen-network-config-base.sh cheqd 2 0 0 # 2 validators, 0 observers and 0 seeds

# Change ports for validator-1
sed -i.bak 's|laddr = "tcp://0.0.0.0:26656"|laddr = "tcp://0.0.0.0:26666"|g' network-config/validator-1/config/config.toml
sed -i.bak 's|laddr = "tcp://0.0.0.0:26657"|laddr = "tcp://0.0.0.0:26667"|g' network-config/validator-1/config/config.toml
sed -i.bak 's|pprof_laddr = "localhost:6060"|pprof_laddr = "localhost:6070"|g' network-config/validator-1/config/config.toml

sed -i.bak 's|address = "0.0.0.0:9090"|address = "0.0.0.0:9100"|g' network-config/validator-1/config/app.toml
sed -i.bak 's|address = "0.0.0.0:9091"|address = "0.0.0.0:9101"|g' network-config/validator-1/config/app.toml
sed -i.bak 's|address = "tcp://0.0.0.0:1317"|address = "tcp://0.0.0.0:1327"|g' network-config/validator-1/config/app.toml
sed -i.bak 's|address = ":8080"|address = ":8090"|g' network-config/validator-1/config/app.toml

# Set peers
VAL_0_ID=$(cheqd-noded tendermint show-node-id --home "network-config/validator-0")
PERSISTENT_PEERS="$VAL_0_ID@127.0.0.1:26656"
sed -i.bak "s/persistent_peers = \"\"/persistent_peers = \"$PERSISTENT_PEERS\"/g" network-config/validator-1/config/config.toml
