# Buf Gen for Swagger

version: v1

plugins:
  - name: swagger
    out: ../api/docs
    opt:
    - fqn_for_swagger_name=true
    - include_package_in_tags=true
    - json_names_for_fields=true
    - logtostderr=true
    - simple_operation_ids=true
