gas_adjustment = 1
provider_timeout = "1000000s"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "cheqd"]]
service-name = "price-feeder"
prometheus-retention-time = 100

[[provider_endpoints]]
name = "mexc"
rest = "http://localhost:8080"
websocket = "localhost:8080"

[[provider_endpoints]]
name = "coinbase"
rest = "https://api.exchange.coinbase.com"
websocket = "ws-feed.exchange.coinbase.com"

## The application currently uses two providers: MEXC and Coinbase.
## You can update the rest and websocket endpoints for these providers as needed.
