config_dir = "ojo-provider-config"

gas_adjustment = 1
provider_timeout = "1000000s"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[account]
address = "cheqd1jvfm45nwpgvxg4m2r5l80j5my87uc54mkzsg6h"
chain_id = "cheqd"
validator = "cheqdvaloper1jvfm45nwpgvxg4m2r5l80j5my87uc54mfgwwu4"

[keyring]
backend = "test"
dir = "/home/vitwit/.cheqdnode"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "cheqd"]]
service-name = "price-feeder"
prometheus-retention-time = 100
