name: "Lint PR"
on:
  pull_request_target:

jobs:

  semantic-pr-check:
    runs-on: ubuntu-latest
    name: "Semantic PR check"
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
