name: "cheqd-node CI: Lint code and run unit tests"

on:
  push:
    paths-ignore:
    - '**.md'
    - 'docs/**'
    - 'architecture/**'
    - '.gitbook/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Get dependencies # Fix for `Running error: context loading failed: no go files to analyze` from `golangci-lint`
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          args: --timeout 5m0s

  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Run tests
        run: go test -v ./...
