name: cheqd-node CI (pull request)

on: 
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'docs/**'
    - 'architecture/**'
    - '.gitbook/**'

jobs:
  build-and-setup:
    # name: Build deb, images and set up docker pool
    uses: cheqd/cheqd-node/.github/workflows/reusable-build-and-setup.yml@main

  cosmos-and-identity-tests:
    needs: build-and-setup
    # name: Run cosmos and identity tests
    uses: cheqd/cheqd-node/.github/workflows/reusable-cosmos-and-identity-tests.yml@main
