name: cheqd-node CI (push)

on: 
  push:
    paths-ignore:
    - '**.md'
    - 'docs/**'
    - 'architecture/**'
    - '.gitbook/**'

jobs:
  lint-and-test:
    # name: Lint code and run unit tests
    uses: cheqd/cheqd-node/.github/workflows/reusable-lint-and-test.yml@split-workflows
