name: "PR Title Check"
on:
  pull_request_target:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: "Run Go tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: run tests
        run: go test -v -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
  #  lint-pr:
#    name: "PR format check"
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      # check for the most recent release: https://github.com/CondeNast/conventional-pull-request-action/releases
#      # replace vX.X.X below with the most recently released version
#      - uses: CondeNast/conventional-pull-request-action@v0.1.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          # to override config-conventional rules, specify a relative path to your rules module, actions/checkout is required for this setting!
#          commitlintRulesPath: "./.github/linters/.commitlint.rules.js" # default: undefined
#          # if the PR contains a single commit, fail if the commit message and the PR title do not match
#          commitTitleMatch: "false" # default: 'true'
