name: Lint code and run unit tests

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          args: --timeout 5m0s

  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          PACKAGES=$(go list ./...)
          go test -v $PACKAGES
